/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_exp03;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testApp() {
        assertNotNull("app should have a greeting", true);
    }
}
